# Generated by Django 3.0.4 on 2020-03-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dicty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_source', models.CharField(max_length=500)),
                ('cluster_1', models.IntegerField()),
                ('cluster_2', models.IntegerField()),
            ],
        ),
    ]
