# Generated by Django 3.0.4 on 2020-03-14 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dicty',
            new_name='News',
        ),
    ]
